name: TryHackMe Badge Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "RobMad"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output_path: "README.md"
          badge_url: "https://tryhackme-badges.s3.amazonaws.com/${username}.png"
